Login.vueの作成
Recursion-Group-G/Othello pull request #13
Opened 2021-11-02 09:10 UTC by kuro1221

Login.vue作成を行いました。
レビューお願いします。

ワイヤーフレームに近いデザインになるようコーディングしています。
PC表示とスマホ表示のみ対応させています。

2021-11-02 09:30 UTC, mcnLeandro requested changes
レビューしました！
確認お願いします！

コミットし終わったらもう一度レビューリクエストお願いします！

2021-11-02 09:30 UTC, mcnLeandro commented on src/views/Login.vue
> +      <button class="button">Game Start</button>
2行目に対応するdivが抜けちゃってます！

2021-11-02 09:30 UTC, mcnLeandro commented on src/views/Login.vue
> +<template>
曖昧な説明で誤解させてしまったかもしれないです🙏

せっかく環境が整っているので
vuetifyを使いましょう！！

2021-11-03 02:43 UTC, kuro1221 commented
Vuetifyで作成しましたので確認お願いします！

2021-11-03 02:44 UTC, kuro1221 commented
[](url)
![Uploading スクリーンショット 2021-11-03 11.44.03.png…]()

2021-11-03 03:08 UTC, mcnLeandro approved these changes
みました！

いい感じですね！
.gitignoreにあった.prettierrcは全員共通のものを利用したいので、今はいいですが、後のタスクで削除します！

2021-11-03 03:10 UTC, merged

2021-11-03 03:10 UTC, mcnLeandro commented
![sshot](https://user-images.githubusercontent.com/72016706/140005069-d8460a15-aac0-4ed9-bda8-508bdfc0fbdf.png)