Router追加#15
Recursion-Group-G/Othello pull request #21
Opened 2021-11-06 00:39 UTC by kuro1221

vue-router追加しました。
各ページのボタンに、次ページへのリンクを追加しています。

vue routerをinstallしたため、npm install必要です。

2021-11-06 01:38 UTC, mcnLeandro requested changes
ありがとうございます！
どっちがいんだろうと調べていたんですが、hrefよりrouter-linkの方が好ましいみたいです
https://router.vuejs.org/ja/api/#router-link
修正お願いします！！

2021-11-06 01:38 UTC, mcnLeandro commented on src/views/Login.vue
> +                        <v-btn
router-linkでお願いします！

2021-11-06 01:38 UTC, mcnLeandro commented on src/views/Top.vue
> +                        href="/#/login"
router-linkでお願いします！

2021-11-06 10:32 UTC, kuro1221 commented
router-linkで追加しました。
ただしボタンの文字へのCSSが当たらなくなる件についてはimportantで対応しています。
vue-routerのモードはヒストリーに設定しています。

2021-11-06 13:41 UTC, mcnLeandro requested changes
何度もすみません！
もう一度こちら確認お願いお願いできますか？

2021-11-06 13:41 UTC, mcnLeandro commented on src/views/Top.vue
> +                        href="/#/login"
```
<router-link to="/login" class="button-link">
                        <v-btn
                            class="deep-purple accent-3 white--text"
                            depressed
                            elevation="24"
                        >
                            Start
                        </v-btn>
                    </router-link>
                    ```

2021-11-06 13:41 UTC, mcnLeandro commented on src/views/Login.vue
> +                        <v-btn
```
<v-row class="justify-center">
                        <router-link to="/game" class="button-link">
                            <v-btn
                                dark
                                large
                                color="deep-purple"
                            >
                                Game Start
                            </v-btn>
                        </router-link>
                    </v-row>
                    ```

2021-11-06 13:41 UTC, mcnLeandro commented on src/views/Login.vue
> +
ここのCSSもなしでいけました！

2021-11-07 00:27 UTC, kuro1221 commented
こちらこそすみません。
おかげでimportant使わなくてもcss適用することができました。

2021-11-07 02:30 UTC, mcnLeandro approved these changes
OKです！
ありがとうございます！

2021-11-07 02:31 UTC, merged