Tucker pop up html
Recursion-Group-G/Othello pull request #33
Opened 2021-11-08 03:02 UTC by mcnLeandro

レスポンシブ対応も完了したのでプルリク送ります！
<img width="957" alt="sshot" src="https://user-images.githubusercontent.com/72016706/140677562-f2fe7c5c-2808-41ba-a83d-5cb089c9013d.png">
<img width="407" alt="sshot" src="https://user-images.githubusercontent.com/72016706/140677574-24e2a17f-857f-4224-95e9-fc5c03b17f10.png">

2021-11-08 14:16 UTC, kuro1221 commented on src/components/PopUp.vue
> +                            <v-btn
こちらを参考にTOPボタンの<v-btn>タグを<router-link>タグで囲って、Topページへのリンクを追加してください！
RETRYボタンも同様にGAMEページへのリンク追加お願いします！
https://github.com/Recursion-Group-G/Othello/pull/21

2021-11-08 14:18 UTC, kuro1221 requested changes
Vueファイルの作成はOKです！
少しだけ修正お願いします！

2021-11-10 08:53 UTC, Tucker263 commented
pushしたのですが、このようなリンクの貼り方でよろしいでしょうか？

2021-11-10 14:53 UTC, kuro1221 commented
追加で申し訳ないですが、router.tsのroutesにPopUp.vueのコンポーネントを登録お願いできればと思います！

2021-11-11 13:38 UTC, Tucker263 commented
コンポーネントを登録しました！

2021-11-11 14:55 UTC, mcnLeandro commented
@kuro1221 
🙏
PopUpはページではないのでrouterに追加は必要ないです！！
aタグでリンクで作成されているので、router-linkに治すようにレビューしてあげてください！！

2021-11-11 15:13 UTC, Tucker263 commented
router.tsから削除しました！

2021-11-11 15:35 UTC, Tucker263 commented
2点を修正しました！

2021-11-12 12:48 UTC, kuro1221 commented
コードはOKです！
package-json.lockがコンフリクトしてるので以下のコマンドを入力してから、pushしてください！
```git checkout develop

git pull origin develop --rebase

git checkout Tucker pop up html

git merge --no-ff master

npm install (もしくはyarn install)
```

2021-11-12 15:49 UTC, Tucker263 commented
コマンドを実行して、pushしました！

2021-11-12 16:16 UTC, mcnLeandro commented
@Tucker263 
pushしてますか？？
コミットが見当たらないです笑笑

2021-11-13 04:15 UTC, merged