first commit login.vue data
Recursion-Group-G/Othello pull request #43
Opened 2021-11-11 15:13 UTC by m2mt-l

一旦login.vue data作りました。
以下は後ほど実装します。
・名前を入力しない時のメッセージ表示(rulesを利用)
・Game ModeとColorが未選択、名前空欄時には次のページに行かない
・Mode選択時の動的な描画(VS CPUだったらPlayer1しか表示させない)
・色の選択の連動(Player1がwhiteを選択したら、Player2はblackしか選択できない)

2021-11-11 15:53 UTC, mcnLeandro reviewed
作成中だと気づかずに余計なコメントまでしてしまったかもです！一応確認ください！
途中経過をこんな感じで共有してくれると助かります！🙏

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +            playerInfo: {
ここはv-forで使うplayersをplayerInfoの代わりに用意します！
そしてそのプレイヤー自体をv-modelに設置する感じですね！

なので

```js
players: new Array(config.player.number.min)
                .fill(new Player("", ))
                 //ミスりました、playerのコンストラクターはnameとcolorのみであとはデフォルト値がわかるはずなのでそこも修正お願いしたいです！ colorに関してnullを許容するかはお任せします！
```
こうしたいところですが、これだと一つのプレイヤーのメモリアドレスで全部埋める形になるので、こうします
```js
players: new Array(Config.player.number.min)
                .fill({})
                .map(() => new Player()),
```

っていう裏技でした笑笑
でも普通にfor分で配列作成するメソッド作ってしまっても問題ないです！

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +                    <!--Player1 #Player情報はv-forで書き直し？-->
そうですね！
`v-for player in players`
みたいに書きましょう！

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +                    <!--Select Mode-->
<img width="711" alt="sshot 7" src="https://user-images.githubusercontent.com/72016706/141324463-21e4ef7a-b4e9-4870-aee6-db7ba6c3d310.png">

GameMode,Player1のセクション,Player2のセクションにそれぞれ余白をあけてあげるともっとみやすくなると思います！

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +
Discordでも言われていた通り
最後に lintを通しておきましょう！

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +                    <!--Player1 #Player情報はv-forで書き直し？-->
playersのデータについては他の部分で言及しています！

2021-11-11 15:53 UTC, mcnLeandro commented on src/views/Login.vue
> +            initialScore: 2,
`initialScore`
これはconfig行きかもですね笑笑
しかもPlayer作成時にデフォルトで追加してあげるといいかもしれないです！!

2021-11-11 15:56 UTC, mcnLeandro commented on src/views/Login.vue
> +            playerInfo: {
これで最後にemit(this.players)で行けるので簡単ですね！

2021-11-12 01:55 UTC, m2mt-l commented on src/views/Login.vue
> +            playerInfo: {
最初からplayersのオブジェクトをv-modelで操作したかったのですが、このデータのやり取り方法が思いつかず最初dataに入力情報を入れてから作成してました。おかげさまでコードがすっきりしました！

2021-11-12 01:55 UTC, m2mt-l commented on src/views/Login.vue
> +                    <!--Player1 #Player情報はv-forで書き直し？-->
修正してますので確認お願いします！

2021-11-12 01:56 UTC, m2mt-l commented on src/views/Login.vue
> +                    <!--Select Mode-->
余白追加しました！

2021-11-12 01:56 UTC, m2mt-l commented on src/views/Login.vue
> +
次からは忘れません笑

2021-11-12 01:57 UTC, m2mt-l commented on src/views/Login.vue
> +            initialScore: 2,
configに入れました！その他少しconfig修正してるので確認をお願いします！

2021-11-12 03:39 UTC, mcnLeandro requested changes
ちょっと多くなってしまいましたが確認お願いします！！

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +        },
ここはこういう感じにしましょう！
```
const color =  this.players[Config.player.playerIndex].color
if(...)
else
`````

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +                this.switchCpuPlayer(this.players[Config.player.cpuIndex]); //ConfigにCPUがどこになるのかIndex追加
'versusCPU' はconfigから参照しましょう！

あとlintした時に省略if文が改行されてます！この場合は エラーの原因にならないうちに {} で囲っちゃった方がいいと思います！

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +        },
そうですね。。
ValidationCheckみたいなモジュールを作成して、App.vueにデータを送る前にチェックを挟むといいかもしれないですね🤔
これは別のタスクで作成しても、今作成しても、どちらでも問題ないです!

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +                    () => new Player('', Config.player.initialScore, '', false)
ここは今はまだいいのかなと思うのですが、もし今後
```
new Player('', Config.player.initialScore, '', false)
```
以外の初期値で作成する場面がなければcontroructor内で受け取るparamterを全て削除してクラスのメンバ変数の初期値を固定にしてもいいかもしれないですね。

m2mtさんどう思いますか？？

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +                        ></v-select>
またPlayerでミスを発見しました😭
今、Playerのcolorはstringになっていると思うんですが、前決めた結果

```
interface Color {
    code: string;
    id: number;
}
```

colorはColorなのでそこの修正お願いしたいです🙏

2021-11-12 03:39 UTC, mcnLeandro commented on src/views/Login.vue
> +                        ></v-select>
これに伴って、「select内のoptionではwhite or blackって表示させたいけど、実際にPlayerのcolorに設置したいのはColorオブジェクト(inteface通り)」っていうことが起きると思います！

申し訳ないですが、これを実現してほしいです！
https://jp.vuejs.org/v2/guide/forms.html#%E9%81%B8%E6%8A%9E%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3

ちなみにこの場合、:itemsではなく、optionをv-forで回す形になると思います。

ちょっと複雑で混乱しちゃうかもですがお願いしたいです！
わからなかったら言ってください！

2021-11-12 09:17 UTC, m2mt-l commented on src/views/Login.vue
> +                        ></v-select>
PlayerでColorをオブジェクトで持つのは異論ないのですが、selectのオプションをオブジェクトのColorで指定するとデータの流れがおかしくないですか？
whiteかblackの選択をした時点でColorのオブジェクト内の値が決まるはずで、それが決まってない時点でColorを参照は出来ないと思いますがどうでしょうか？selectの情報はconfig内のcolorからひいていいるので矛盾が生じることはないと思います。
```
            colors: Object.keys(Config.stone.color),
```

2021-11-12 10:43 UTC, mcnLeandro commented on src/views/Login.vue
> +                        ></v-select>
vuetifyのv-selectを使っているのをすっかり忘れていました😅
それでも今調べた結果、こんな感じに対応できるみたいです！
https://vuetifyjs.com/ja/components/selects/#section-30b530f330d730eb

```js
<template>
   
<v-select
    :key="index"
    v-model="player.color"
    :items="colors"
    item-text="name"
    item-value="obj"
    :label="`Color (Player${index + 1})`"
></v-select>
                   
</template>

<script lang="ts">
import Vue from 'vue';
import Player from '../models/player';
import Config from '../config';

export default Vue.extend({
    name: 'Login',
    data() {
        return {
           //少しデータを整形します。
            colors: Object.keys(Config.stone.color).map(colorString=>{
                return {
                    name: colorString,
                    obj: Config.stone.color[colorString],
                }
            }),
        };
    },
});
</script>

```

2021-11-12 12:16 UTC, m2mt-l commented on src/views/Login.vue
> +                        ></v-select>
ありがとうございます！あとで試してみます！
PlayerのcolorをColorに置き換えを行っていますが、下記のようなコードになってしまいます。。。Playerのcolorの名前変えますか(haveStoneとか)
```ts
        judgeCpuColor(): string {
            if (this.players[Config.player.playerIndex].color.color.code === Config.stone.color.white.code){
                return 'black';
            }else if (this.players[Config.player.playerIndex].color.color.code === Config.stone.color.black.code){
                return 'white';
            }else return ''; //nullにするとplayer.colorにもnullの型指定追加が必要なので一旦初期値にしてます。どこかでエラー処理を書いた方がいいかもしれないです。
        },
```

2021-11-12 12:27 UTC, mcnLeandro commented on src/views/Login.vue
> +                        ></v-select>
```js
player.color = {
  code: ""
  id:
}
```
という認識なのでcolor.colorのようにならないかと思いました！
実際は重複しちゃっていましたか？

2021-11-12 12:38 UTC, m2mt-l commented on src/views/Login.vue
> +                        ></v-select>
ちゃんと入っているようには見えるのですが、colorを指定しないとアクセスできないっぽいです。一旦これでpushします。その他の箇所はほぼ直してます！
![Screen Shot 2021-11-12 at 21 36 37](https://user-images.githubusercontent.com/6548931/141468405-3b44b6c6-40d8-482e-9fc9-5d1ff508e9f2.png)

2021-11-12 12:42 UTC, m2mt-l commented on src/views/Login.vue
> +        */
削除してます！

2021-11-12 12:43 UTC, m2mt-l commented on src/views/Login.vue
> +            ],
config入れました！

2021-11-12 12:43 UTC, m2mt-l commented on src/views/Login.vue
> +                this.switchCpuPlayer(this.players[Config.player.cpuIndex]); //ConfigにCPUがどこになるのかIndex追加
修正してます！

2021-11-12 13:11 UTC, mcnLeandro commented on src/views/Login.vue
> +        },
https://github.com/Recursion-Group-G/Othello/issues/48

2021-11-12 13:41 UTC, mcnLeandro requested changes
レビューしました！！💪
自分が把握していなくて申し訳ないですが、他に実装する部分がなければこれでラストなはずです！

2021-11-12 13:41 UTC, mcnLeandro commented on src/views/Login.vue
> +                    </template>
コンソール確認したらエラーが出ていたので修正しておきましょう！

```js
tamplate -> div
                  <div v-for="(player, index) in players" :key="index">
                        <v-text-field
                            class="mt-10"
                            v-model="player.name"
                            :counter="10"
                            :label="`Name (Player${index + 1})`"
                            required
                        ></v-text-field>
                        <!--後ほどプレイヤー毎の選択により連動するselectに変更-->
                        <v-select
                            v-model="player.color"
                            :items="colors"
                            item-text="name"
                            item-value="obj"
                            :label="`Color (Player${index + 1})`"
                        ></v-select>
                    </div>
 ```

2021-11-12 13:41 UTC, mcnLeandro commented on src/views/Login.vue
>              <v-row justify="center">
ごめんなさい。スタイル作成の時の確認ミスで
2-3行目の
v-appとv-contentが重複しているのでv-app削除 v-contentをdivに変更お願いしたいです！

2021-11-12 13:41 UTC, mcnLeandro commented on src/views/Login.vue
> +                this.switchCpuPlayer(this.players[Config.player.cpuIndex]); //ConfigにCPUがどこになるのかIndex追加
こういうことでした！！
もしかして、lintの時に消されちゃってますか？？
```js
 if (this.selectedMode.modeName === 'versusCPU'){
                this.switchCpuPlayer(this.players[Config.player.cpuIndex]);
 }
 ```

2021-11-12 13:41 UTC, mcnLeandro commented on src/views/Login.vue
> +        },
https://github.com/Recursion-Group-G/Othello/pull/43/files/69fc58e62c15d3752b7677db399a28aefc3a7692#r748231811

自分の環境で試した結果うまくいきました！
こんな関数にしてあげてください！
```js
        judgeCpuColor(): Color {
            const color = this.players[Config.player.playerIndex].color //もしくはidまでいってもいいです
            if (color.id === Config.stone.color.white.id){
                return Config.stone.color.black;
            }
            else if (color.id === Config.stone.color.black.id){
                return Config.stone.color.white;
            }
            else return {}; //nullにするとplayer.colorにもnullの型指定追加が必要なので一旦初期値にしてます。どこかでエラー処理を書いた方がいいかもしれないです。
        },
```

2021-11-12 14:10 UTC, m2mt-l commented
やはりStoneとして認識されてしまいます。その他変えた場所ありますか？
![Screen Shot 2021-11-12 at 23 07 55](https://user-images.githubusercontent.com/6548931/141480117-36cda221-6e58-40db-ae30-15a0a3546b66.png)

2021-11-12 14:40 UTC, mcnLeandro commented
functionの返り値の指定をStoneにしていませんか？？
`judgeCpuColor(): Color ` みたいかどうか確認していただきたいです！
あと、これによって今の所104行目は削除するしかなさそうです！

2021-11-12 14:43 UTC, m2mt-l commented
ちゃんとColorは指定してます。画面表示自体は出来て動作はするのですが、かなりエラーが出てる状態です。
```ts
        judgeCpuColor(): Color {
            const color = this.players[Config.player.playerIndex].color;
            if (color.id === Config.stone.color.white.id){
                return Config.stone.color.black;
            }
            else if (color.id === Config.stone.color.black.id){
                return Config.stone.color.white;
            }
            else return {}; 
```

2021-11-12 14:54 UTC, mcnLeandro commented
なるほど、推測ですが、stoneファイルからintefaceをimportしてるのが関係ありそうですね！
動作しているので別のタスク対応することにします。

タスク内容はinterfaceディレクトリの作成とそれに伴うファイルの編集ですかね。。

共有ありがとうございます。

ひとまず方指定はせずにちょっとwarningが出るかもしれませんが
```js
judgeCpuColor(){
...
}
```
こんな感じで、pushしていただきたいです！！
最後にlintも通しておいてくださいね 👍 :

2021-11-12 22:48 UTC, m2mt-l commented on src/views/Login.vue
> +                    </template>
修正してます！

2021-11-12 22:48 UTC, m2mt-l commented on src/views/Login.vue
>              <v-row justify="center">
修正してます！

2021-11-12 22:50 UTC, m2mt-l commented
一旦エラーが出ないように以下に書き換えてます。コメントには修正予定のコードを残していています。
```ts
            const color = this.players[Config.player.playerIndex].color.color;
            if (color.id === Config.stone.color.white.id){
                return new Color({code: Config.stone.color.black.code, id: Config.stone.color.black.id});
            }
            else if (color.id === Config.stone.color.black.id){
                return new Color({code: Config.stone.color.white.code, id: Config.stone.color.white.id});
            }
            else return new Color({code: '', id: 0}); //nullにするとplayer.colorにもnullの型指定追加が必要なので一旦初期値にしてます。どこかでエラー処理を書いた方がいいかもしれないです。
```

2021-11-13 00:44 UTC, mcnLeandro commented on src/views/Login.vue
> +        },
#49

2021-11-13 00:47 UTC, mcnLeandro reviewed
レビューしました！
OKです！
他に実装する部分がなければマージしますが、どうですか？？

2021-11-13 00:52 UTC, mcnLeandro approved these changes
一旦マージすることにしました！
・名前を入力しない時のメッセージ表示(rulesを利用)
・Game ModeとColorが未選択、名前空欄時には次のページに行かない
・Mode選択時の動的な描画(VS CPUだったらPlayer1しか表示させない)
・色の選択の連動(Player1がwhiteを選択したら、Player2はblackしか選択できない)
こちら実装する際は同じブランチで続けていただいて問題ないです！

2021-11-13 00:53 UTC, m2mt-l commented
ありがとうございます！以下issue立ててるので後ほど実装します！
https://github.com/Recursion-Group-G/Othello/issues/52

2021-11-13 00:57 UTC, merged