Board link module
Recursion-Group-G/Othello pull request #55
Opened 2021-11-13 15:54 UTC by Tucker263

一通り実装できたと思うので、確認をお願いします！
議論の後、考えたのですが、
builderパターンの方がわかりやすい気がしたので、それを使いました。

2021-11-13 17:03 UTC, mcnLeandro reviewed
ありがとうございます！！
OOPはtuckerさんの方が知識は上かなと思うので違うこと言ってたら申し訳ないです！
その時はコメントください！

2021-11-13 17:07 UTC, mcnLeandro commented
@Tucker263 
あと、コミットメッセージは、もっと具体的なメッセージをするように心がけてください！
例えば
`BoardBuilder.setSquaresメソッド作成`
`BoardBuilder.setSquaresでエラーが出ていたので修正`

できるだけ、何を変更したのかや、なぜ変更したのかを書くといいです！
自分はこれをいつも参考にしています！

2021-11-13 17:21 UTC, mcnLeandro commented
あと、もう一つ、作成される配列がどういう座標で作成されるのかをコメントアウトに追加しておいてください！
おそらく今作成している二次元配列の場合は左上が(0,0)で右下に大きくなってるはずです。
なので、自分だったらこれを残します笑笑
```js
/**
 *   (0,0)
 *   *____________
 *   |__|__|__|__|
 *   |__|__|__|__|
 *   |__|__|__|__|
 *   |__|__|__|__|
 *   |__|__|__|__|
 *               
 */
 ```

2021-11-14 15:58 UTC, Tucker263 commented
getter関数の追加以外は修正しました！
オブジェクトを組み立てるだけのクラスなので、必要ないと思ったためです！

2021-11-15 01:25 UTC, mcnLeandro requested changes
レビューしました！
このレビュー対応ができたら完成の予定です！💪

2021-11-15 01:25 UTC, mcnLeandro commented on src/modules/boardBuilder.ts
> +                squareX.push(new Square({x: x, y: y}));
僕のミスですが、SquareモデルのisEmptyのデフォルトがfalseになっているのでtrueに変更しておいていただきたいです！

2021-11-15 01:25 UTC, mcnLeandro commented on src/modules/boardBuilder.ts
> +                if(canInsertTopRight) curr.topRight = this.squares[y - 1][x + 1];
かなり読みやすくなったんですが、 `this.squares[y - 1][x + 1];` みたいにまだマジックナンバーがあります！！

他の部分でも使っているy-1はどう言う意味かというと、おそらくcurrのyより一個上と言う意味があるので、それぞれ

```js
const top = y-1
const right = x+1
const left = x-1
const bottom = y+1
```
が作れるはずです！

2021-11-15 01:25 UTC, mcnLeandro commented on src/modules/boardBuilder.ts
> +                if(canInsertBottomLeft) curr.bottomLeft = this.squares[y + 1][x - 1];
npm run lint を通しておきましょう！！

2021-11-15 06:52 UTC, Tucker263 commented
レビュー対応で全て修正できたと思います！
個人的にcanInsertTop周辺の部分が長くて、読みにくそうだと思うのですが、どうでしょうか？

2021-11-15 07:59 UTC, mcnLeandro commented on src/modules/boardBuilder.ts
> +                const canInsertBottomLeft : boolean = x > 0 && y < this.size.y - 1;
そうですね。
一応読みやすくなっているとは思うんですが、確かにまだ改善できると思います！
僕が前回レビューした観点から言うと、`this.size.x -1` って言うのは indexのmaxみたいな意味だったと思います！

しかもindexのmaxとか、minとかってthis.sizeが決まった時点で決まるものなので、for文内で定義するべきでないですよね！

いろんな解決策があると思うんですが、普通にfor分の外でhashMapで定義しておくといいですね！

```js
const index = {
  x:{
    min:0
    max: this.size.x -1
  }
  y:{
    min:0
    max: this.size.y-1
  }
}



for
  for
  //if文に直接書くかは任せます！
    const canInsertRight = x < index.x.max
```

2021-11-15 09:32 UTC, Tucker263 commented
レビューを参考にして、改善しました！どうでしょうか？？

2021-11-15 09:54 UTC, mcnLeandro approved these changes
ありがとうございます！
これでOKです！マージします

インデントせっかく整えていただいたんですが、lintしたら元に戻っちゃうかもしれいないですね😭

2021-11-15 10:13 UTC, merged