Create stone style
Recursion-Group-G/Othello pull request #56
Opened 2021-11-14 13:17 UTC by mcnLeandro

- Stoneコンポーネントの作成
- flipAnimation用にThreeConfig追加
- flipAnimationのスマホ対応(出てくる位置が違ったのを修正)

を行いました！
レビューお願いします！

2021-11-15 23:03 UTC, m2mt-l requested changes
遅くなりましたが内容見ました！確認お願いします！

2021-11-15 23:03 UTC, m2mt-l commented on src/components/Stone.vue
> +            color: "#000000"
このcolorは仮ですかね？コメント入れてほしいのとConfigからデータを指定してほしいです！

2021-11-16 02:24 UTC, mcnLeandro commented on src/components/Stone.vue
> +            color: "#000000"
そうです！仮です！
コメント追加しておきました！

2021-11-16 02:25 UTC, mcnLeandro commented
再レビューお願いします！

2021-11-16 03:12 UTC, m2mt-l approved these changes

2021-11-16 03:29 UTC, m2mt-l commented
mergeしようとしてるのですが、下記エラーが出てしまいます。
```
 ! [rejected]        develop -> develop (non-fast-forward)
error: failed to push some refs to 'git@github.com:Recursion-Group-G/Othello.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
![Uploading Screen Shot 2021-11-16 at 12.14.30.png…]()

2021-11-16 04:13 UTC, mcnLeandro commented
お！そしたら自分が対応してみますね！

2021-11-16 04:16 UTC, mcnLeandro commented
```
git pull --no-ff origin develop
``
![sshot](https://user-images.githubusercontent.com/72016706/141910511-be7bd900-5ad5-4f5e-8e82-181325001f93.png)
`

2021-11-16 04:22 UTC, mcnLeandro commented
コンフリクト解消後
```
git add .
git commit
```

![sshot](https://user-images.githubusercontent.com/72016706/141913898-0d77947d-4bad-4052-bac6-4f3c6633bdf8.png)
自分はいつもこのままctl+Xでコミットしてます。(nanoの場合)

2021-11-16 04:24 UTC, mcnLeandro commented
最後にpushしたらOKです！

2021-11-16 04:25 UTC, mcnLeandro commented
もし、今どこにもブランチ切り替えれない状況だったり
「resolve confilict before ~~」みたいに出ていたら
```
git merge --abort
```
でマージを止めることができます！

2021-11-16 04:25 UTC, merged