Create interface
Recursion-Group-G/Othello pull request #57
Opened 2021-11-14 13:20 UTC by kuro1221

以下のissueの実装として、interfaceを作成するリファクターを行いました。
https://github.com/Recursion-Group-G/Othello/issues/49

srcディレクトリ直下にinterfacesディレクトリを作成しています。

2021-11-14 13:42 UTC, mcnLeandro requested changes
ありがとうございます！助かります！
気になる点があったので確認お願いしたいです！

2021-11-14 13:42 UTC, mcnLeandro commented on src/interfaces/config.ts
> +        };
Colorインターフェースをimportして
```
color:
   [key: string]: Color
```
でいけそうです！

2021-11-14 13:42 UTC, mcnLeandro commented on src/interfaces/config.ts
> +        size: {
ここも
size: Size　でOKそうですね！

2021-11-14 13:42 UTC, mcnLeandro commented on src/interfaces/config.ts
> +        size: {
そういえば、このsuquareのsizeって何を表しているんでしたっけ
widthとかheightとかなら必要かもですが。使っていないのであれば
もしかしたらいらないのかもしれないです。

2021-11-15 10:32 UTC, kuro1221 commented on src/interfaces/config.ts
> +        size: {
今は使っていないようですが、消していいものなのか.......
判断に迷う場合は別のissueにするべきですかね？

2021-11-15 10:32 UTC, kuro1221 commented
config.tsを修正しました！

2021-11-15 10:48 UTC, mcnLeandro commented on src/interfaces/config.ts
> +        size: {
そうですね！
一旦別タスクにできると思うので今回は触らずに進めますね！
#58

2021-11-15 10:51 UTC, mcnLeandro approved these changes
OKです！
マージします！！

2021-11-15 10:57 UTC, merged