fix: checkOneDirection
Recursion-Group-G/Othello pull request #78
Opened 2021-11-24 12:25 UTC by m2mt-l

ご指摘の箇所の修正を行いました！
インスタンス化はrefactorとしてくろさんのExtension filipをマージしてからやろうと思います。
あと最新版のdevelopのboardBuilder.tsで出ているエラーを修正しているので、マージする時はこちらでマージしていただけますでしょうか？

2021-11-24 13:02 UTC, m2mt-l commented
break入れ忘れていたので追加しました！
たまたま見つけたのですがこんな書き方できるんですね。。あとで余裕があれば試してみます。
https://qiita.com/hatakoya/items/018afbfb1bd45136618a

2021-11-25 17:06 UTC, kuro1221 requested changes
自分のissueと繋ぎ合わせたところ、他にも修正が必要だったのでお願いします。

2021-11-25 17:06 UTC, kuro1221 commented on src/modules/checkAllowedSquares.ts
> +                while (curr != null && (!isSameColor(curr) || isStoneEmpty(curr))) {
すみません！
currがnullだけではなくcurr.stoneがnullの場合も判定しなければなりませんでした！
他の方向も修正お願いします！     
while (curr != null && curr.stone != null && (!isSameColor(curr) || isStoneEmpty(curr))) {

2021-11-25 17:12 UTC, kuro1221 commented
自分のissueと繋ぎ合わせて気がついたのですが、
checkAllowSquare.tsの41行目に後にallDirectionsをリセットする処理が必要だと思います！
今のままだと前のEnclosureのallDirectionsの情報からisAllowedToPlaceの状態を判定してしまいます！
resetAfterTurnOverメソッドの責任を分割してそれを使ってみてはどうでしょうか！

2021-11-25 23:03 UTC, m2mt-l commented
ありがとうございます！上記指摘の箇所の修正を実施しました！

2021-11-25 23:13 UTC, m2mt-l commented
度々すいません！無駄な書き方をしていたので少し修正しました！

2021-11-26 12:47 UTC, kuro1221 commented
OKです！
ありがとうございました！

2021-11-26 12:47 UTC, merged